name: Get environment name
description: Generates an environment name based on branch name.

outputs:
  environment:
    description: "Environment name"
    value: ${{ steps.generate.outputs.environment }}

runs:
  using: "composite"
  steps:
    - id: generate
      name: Generate environment name
      shell: bash
      env:
        BRANCH: ${{ github.head_ref }}
      run: |
        if [ '${{ env.BRANCH }}' == '' ]
          then
            git_branch='${{ github.event.ref }}'
          else
            git_branch='${{ env.BRANCH }}'
          fi

          git_branch=${git_branch//refs\/heads\//}
          git_branch=${git_branch//refs\/tags\//}

          #Replaces special characters with dashes (-) for things like environment and tags
          git_branch_sanitized=${git_branch//[^a-zA-Z0-9]/-}
          echo "environment=${git_branch_sanitized,,}" >> $GITHUB_OUTPUT
